### ISSUE TITLE
Invisibles Opacity / Colour & Highlighting Visibility

### ISSUE THREAD

**Issue by AlexIsMaking** [opattison/newbound-warm-syntax#2]
Since the last update (I'm using version 1.1.0 of the theme), invisibles are no longer "subtle"

![image](https://cloud.githubusercontent.com/assets/10284831/22176332/9d85466a-dfff-11e6-9ba1-b68ea7112fcb.png)

And when I highlight text, only the line number, not the text itself is highlighted

![image](https://cloud.githubusercontent.com/assets/10284831/22176341/d3a1c0c0-dfff-11e6-8572-90141d5c6847.png)

_All text in lines 24-27 is highlighted._

This is making the theme pretty difficult to work with, were the changes intentional?

**Comment by AlexIsMaking** [comment]
This issue fixed itself after a second reload of the editor window.

**Comment by opattison** [comment]
@aplssf Glad it worked out fine! I’ve often had issues like this with Atom extensions: it’s sometimes hard to know exactly when you have a fresh window that is working properly with installed extensions.

**Comment by AlexIsMaking** [comment]
Turns out, it wasn't just me. I'm experiencing this issue again today, having reloaded the window & restarted my laptop. As you can imagine, it's pretty difficult to work in the editor while the invisibles aren't invisible 😬

Are there any details I can post to help with troubleshooting? I'm working in v 1.12.9 of Atom.

**Comment by opattison** [comment]
Ah, I think this may have to do with changes in Atom 1.13 vs 1.12. I changed certain values since they deprecated certain CSS classes starting with 1.13 and onward.

Have you tried updating Atom to 1.13? I believe it will fix any issues you are having. I think it has been out for a couple of weeks now, so it should be available with a quick ”check for update” and restart.

**Comment by opattison** [comment]
By the way, sorry this caused an issue for you. Anyone on 1.13 was getting deprecation warnings logged, and I suppose that 1.12 isn’t forwards-compatible with the changes in syntax theme specifications for 1.13.

**Comment by AlexIsMaking** [comment]
No worries, it happens! It didn't help that I wasn't being prompted to install the latest version, perhaps I installed Atom from the zip version last time. Thanks for the pointers, updating to 1.13 seems to have fixed the issue 🎉

**Comment by opattison** [comment]
Thanks for pointing it out though. I should have realized that earlier versions of Atom might be incompatible with the new syntax, like an API change even though it’s just a naming scheme adjustment. I think [at least one Atom theme](https://github.com/simurai/duotone-dark-forest-syntax/blob/master/package.json) used version compatibility to handle the change.
